version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - xendk
  ignore:
  - dependency-name: symfony/yaml
    versions:
    - 4.4.19
  - dependency-name: symfony/http-client
    versions:
    - 4.4.19
  - dependency-name: symfony/process
    versions:
    - 4.4.19
  - dependency-name: doctrine/dbal
    versions:
    - 2.10.4
