hookfiles: ./tests/dredd/hooks.php
language: vendor/bin/dredd-hooks-php
server: ./scripts/dredd-server.sh
server-wait: 0
init: false
custom: {}
reporter: []
output: []
header: []
sorted: true
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: docs/Assessor API.apib
endpoint: 'http://localhost:8080/'
