FORMAT: 1A

# Assessor

Assessor is the brains of Appocular. It keeps track of snapshots,
checkpoints, batches and images.

Images for visual testing is submitted by creating a batch. A batch is
associated with a snapshot, and images submitted in the batch is put
into checkpoints the on the snapshot. Multiple batches may be run on
the same commit, facilitating multiple test suites or parallel
running.

## Batch resource [/batch]

### Create batch [POST]

Start a new batch run. Returns the id of the new batch. The id
supplied is the snapshot id, ether this batch will be associated with
the snapshot with the given id, or a new snapshot will be created.

Note that the id is case insensitive.

+ Request (application/json)

        {
            "id": "d8f4590320e1343a915b6394170650a8f35d6926"
        }

+ Response 200 (application/json)

        {
            "id": "58444f87-0525-429d-ba3c-d7b06cab748a"
        }

+ Response 422 (application/json)

        {
            "message": "The given data was invalid.",
            "validation_errors": {
                "sha": ["The sha field is required."]
            }
        }

### Delete batch [DELETE /batch/{id}]

Finishes batch run. No further images can be added to this batch, but
further batches on the same snapshot can be created.

+ Parameters

    + id: `58444f87-0525-429d-ba3c-d7b06cab748a` - Batch id.

+ Request (application/json)

+ Response 200

+ Request Batch not found.

    + Parameters

        + id: `invalid`

+ Response 404

### Add image [POST /batch/{id}/checkpoint]

Add checkpoint image. Stores image and associates it with the snapshot
of the current batch run.

+ Parameters

    + id: `58444f87-0525-429d-ba3c-d7b06cab748a` - Batch id.

+ Request (application/json)

        {
            "name": "Frontpage",
            "image": "<base64 PNG data>"
        }

+ Response 200

+ Request Missing name (application/json)

        {
            "image": "<base64 PNG data>"
        }

+ Response 422

        {
            "message": "The given data was invalid.",
            "validation_errors": {
                "name": ["The name field is required."]
            }
        }

+ Request Bad image data (application/json)

        {
            "name": "Frontpage",
            "image": "<bad base64 PNG data>"
        }

+ Response 400 (application/json)

    Base64 data not a valid PNG.

    + Body

            {
                "message": "Bad image data"
            }

## Snapshot resource [/snapshot]

### Get snapshot [GET /snapshot/{id}]

Get information about a snapshot, including checkpoints.

+ Parameters

    + id: `d8f4590320e1343a915b6394170650a8f35d6926` - Id of snapshot.

+ Request (application/json)

+ Response 200

        {
            "id": "d8f4590320e1343a915b6394170650a8f35d6926",
            "checkpoints": [
                {
                    "name": "Frontpage",
                    "image_sha": "3a14fed556280d45d1542e9723d3cc62326c3777"
                }
            ]
        }

+ Request Snapshot not found (application/json)

    + Parameters

        + id: `invalid`


+ Response 404
